services:
  - type: web
    name: diabetes-risk-prediction
    runtime: python
    buildCommand: |
      cd "snp mini/Diabetes_project/Frontend"
      npm install
      npm run build
      cd ../Backend
      pip install -r requirements.txt
    startCommand: cd "snp mini/Diabetes_project/Backend" && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0